from pathlib import Path

import pytest

from imfusion_agent_skills.renderers import AGENTS_END, AGENTS_START, parse_mdc, render_agents


def test_parse_mdc_accepts_crlf() -> None:
	frontmatter, body = parse_mdc(
		"---\r\ndescription: Example\r\nglobs: **/*.cpp\r\nalwaysApply: false\r\n---\r\nBody\r\n"
	)

	assert frontmatter == {
		"description": "Example",
		"globs": "**/*.cpp",
		"alwaysApply": "false",
	}
	assert body == "Body"


def test_render_all_agents_to_native_locations() -> None:
	rendered = render_agents(("cursor", "claude", "opencode"))
	by_path = {item.path.as_posix(): item for item in rendered}

	assert ".cursor/rules/cpp-guidelines.mdc" in by_path
	assert ".cursor/rules/ml-operation-header-template.h" in by_path
	assert ".cursor/skills/create-imfusion-plugin/SKILL.md" in by_path
	assert ".claude/rules/cpp-guidelines.md" in by_path
	assert ".claude/rules/ml-operation-header-template.h" in by_path
	assert ".claude/skills/create-imfusion-plugin/SKILL.md" in by_path
	assert ".opencode/skills/create-imfusion-plugin/SKILL.md" in by_path
	assert ".opencode/references/ml-operation-header-template.h" in by_path
	assert by_path["AGENTS.md"].merge_block
	assert AGENTS_START in by_path["AGENTS.md"].content
	assert AGENTS_END in by_path["AGENTS.md"].content


def test_render_rejects_unknown_agent() -> None:
	with pytest.raises(ValueError, match="windsurf"):
		render_agents(("cursor", "windsurf"))


def _claude_rules() -> dict[str, str]:
	return {
		item.path.name: item.content
		for item in render_agents(("claude",))
		if item.path.suffix == ".md"
	}


def test_claude_scoped_rule_starts_with_frontmatter() -> None:
	# Claude Code ignores frontmatter that is not the very first content in the file.
	rule = _claude_rules()["cpp-guidelines.md"]

	assert rule.startswith('---\npaths:\n  - "**/*.cpp"\n  - "**/*.h"\n  - "**/*.hpp"\n---\n\n')
	assert "Generated by imfusion-agent-skills from cpp-guidelines.mdc" in rule
	assert "\n\n# C++ Guidelines\n" in rule


def test_claude_unscoped_rules_have_no_frontmatter() -> None:
	rules = _claude_rules()

	assert not rules["core-principles.md"].startswith("---")
	assert not rules["public-demos-reference.md"].startswith("---")
	assert rules["core-principles.md"].startswith("<!-- Generated by imfusion-agent-skills")


def test_claude_rules_link_installed_templates() -> None:
	ml_rule = _claude_rules()["ml-operations.md"]

	assert "@ml-operation-header-template.h" not in ml_rule
	assert ".claude/rules/ml-operation-header-template.h" in ml_rule


def test_opencode_block_names_each_rule_and_its_scope() -> None:
	block = {item.path: item.content for item in render_agents(("opencode",))}[Path("AGENTS.md")]

	# Skills refer to rules by name, so the merged block has to keep the names discoverable.
	assert "Rule `cpp-guidelines` (applies to `**/*.cpp`, `**/*.h`, `**/*.hpp`):" in block
	assert "Rule `core-principles` (applies to all files):" in block
	assert "Rule `public-demos-reference` (applies to all files):" in block
	assert "@ml-operation-header-template.h" not in block
	assert "`.opencode/references/`" in block


def test_skills_are_tool_neutral() -> None:
	rendered = {item.path: item.content for item in render_agents(("cursor", "claude"))}

	cursor_skill = rendered[Path(".cursor/skills/create-imfusion-plugin/SKILL.md")]
	claude_skill = rendered[Path(".claude/skills/create-imfusion-plugin/SKILL.md")]
	assert cursor_skill == claude_skill
	assert ".cursor/" not in cursor_skill
