"""Render the bundled guidance into agent-specific project files."""

from __future__ import annotations

import re
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path, PurePosixPath
from typing import Iterable

SUPPORTED_AGENTS = ("cursor", "claude", "opencode")
AGENTS_START = "<!-- imfusion-sdk-agent-kit:start -->"
AGENTS_END = "<!-- imfusion-sdk-agent-kit:end -->"


@dataclass(frozen=True)
class RenderedFile:
	"""A project-relative file produced for one agent."""

	path: Path
	content: str
	agent: str
	merge_block: bool = False


def parse_mdc(text: str) -> tuple[dict[str, str], str]:
	"""Return the frontmatter and body from a Cursor rule."""
	match = re.match(r"^---\r?\n(.*?)\r?\n---\r?\n?(.*)", text, re.DOTALL)
	if not match:
		return {}, text.strip()

	frontmatter: dict[str, str] = {}
	for line in match.group(1).splitlines():
		if ":" not in line:
			continue
		key, _, value = line.partition(":")
		frontmatter[key.strip()] = value.strip()
	return frontmatter, match.group(2).strip()


def _asset_root():
	return files("imfusion_sdk_agent_kit").joinpath("assets")


def _iter_files(directory, prefix: PurePosixPath = PurePosixPath()) -> Iterable[tuple[PurePosixPath, object]]:
	for entry in sorted(directory.iterdir(), key=lambda item: item.name):
		relative = prefix / entry.name
		if entry.is_dir():
			yield from _iter_files(entry, relative)
		elif entry.is_file():
			yield relative, entry


def _read_rules() -> list[tuple[str, dict[str, str], str]]:
	rules = []
	for relative, resource in _iter_files(_asset_root().joinpath("rules")):
		if relative.suffix != ".mdc":
			continue
		frontmatter, body = parse_mdc(resource.read_text(encoding="utf-8"))
		rules.append((relative.stem, frontmatter, body))
	return rules


def _render_skills(agent: str, destination: Path) -> list[RenderedFile]:
	rendered = []
	for relative, resource in _iter_files(_asset_root().joinpath("skills")):
		rendered.append(
			RenderedFile(
				destination / Path(relative.as_posix()),
				resource.read_text(encoding="utf-8"),
				agent,
			)
		)
	return rendered


def _render_references(agent: str, destination: Path) -> list[RenderedFile]:
	rendered = []
	for relative, resource in _iter_files(_asset_root().joinpath("references")):
		rendered.append(
			RenderedFile(
				destination / Path(relative.as_posix()),
				resource.read_text(encoding="utf-8"),
				agent,
			)
		)
	return rendered


def _claude_rule(stem: str, frontmatter: dict[str, str], body: str) -> str:
	header = f"<!-- Generated by imfusion-sdk-agent-kit from {stem}.mdc; do not edit directly. -->\n\n"
	body = body.replace(
		"@ml-operation-header-template.h\n@ml-operation-cpp-template.cpp",
		"ML operation templates are installed next to this rule as "
		"`.claude/rules/ml-operation-header-template.h` and "
		"`.claude/rules/ml-operation-cpp-template.cpp`.",
	)
	always_apply = frontmatter.get("alwaysApply", "false").lower() == "true"
	globs = [glob.strip() for glob in frontmatter.get("globs", "").split(",") if glob.strip()]
	if always_apply or not globs:
		return header + body + "\n"

	paths = "\n".join(f'  - "{glob}"' for glob in globs)
	return f"{header}---\npaths:\n{paths}\n---\n\n{body}\n"


def _render_cursor() -> list[RenderedFile]:
	rendered = []
	rule_assets = _asset_root().joinpath("rules")
	for relative, resource in _iter_files(rule_assets):
		if relative.suffix == ".mdc":
			rendered.append(
				RenderedFile(
					Path(".cursor/rules") / Path(relative.as_posix()),
					resource.read_text(encoding="utf-8"),
					"cursor",
				)
			)
	rendered.extend(_render_references("cursor", Path(".cursor/rules")))
	rendered.extend(_render_skills("cursor", Path(".cursor/skills")))
	return rendered


def _render_claude() -> list[RenderedFile]:
	rendered = [
		RenderedFile(
			Path(f".claude/rules/{stem}.md"),
			_claude_rule(stem, frontmatter, body),
			"claude",
		)
		for stem, frontmatter, body in _read_rules()
	]
	rendered.extend(_render_references("claude", Path(".claude/rules")))
	rendered.extend(_render_skills("claude", Path(".claude/skills")))
	return rendered


def _opencode_body(body: str) -> str:
	return body.replace(
		"@ml-operation-header-template.h\n@ml-operation-cpp-template.cpp",
		"ML operation templates are installed in `.opencode/references/`.",
	)


def _render_opencode() -> list[RenderedFile]:
	rule_bodies = [_opencode_body(body) for _, _, body in _read_rules()]
	block = (
		f"{AGENTS_START}\n"
		"<!-- Generated by imfusion-sdk-agent-kit; edit the source package, not this section. -->\n\n"
		+ "\n\n---\n\n".join(rule_bodies)
		+ f"\n{AGENTS_END}"
	)
	rendered = [RenderedFile(Path("AGENTS.md"), block, "opencode", merge_block=True)]
	rendered.extend(_render_references("opencode", Path(".opencode/references")))
	rendered.extend(_render_skills("opencode", Path(".opencode/skills")))
	return rendered


def render_agents(agents: Iterable[str]) -> list[RenderedFile]:
	"""Render all files for the requested agents in stable order."""
	requested = tuple(dict.fromkeys(agents))
	unknown = sorted(set(requested) - set(SUPPORTED_AGENTS))
	if unknown:
		raise ValueError(f"Unsupported agent(s): {', '.join(unknown)}")

	renderers = {
		"cursor": _render_cursor,
		"claude": _render_claude,
		"opencode": _render_opencode,
	}
	rendered = []
	for agent in requested:
		rendered.extend(renderers[agent]())
	return sorted(rendered, key=lambda item: item.path.as_posix())
